### ISSUE TITLE
What about closed/commercial project

### ISSUE THREAD

**Issue by amerkoleci** [rampantpixels/foundation_lib#14]
Hi,
Excellent work on this library, I would like to use this foundation library as foundation code in my 3D game engine, I cannot understand well the Uni license, can I integrate it into my closed game engine, should I add credit?

Sorry for opening issue but didn't find your mail.

Thanks

**Comment by MJansson** [comment]
This library is in the public domain, so you can do whatever you wish with it, no need to add credits or attribution. I'm glad you find it useful :)

**Comment by amerkoleci** [comment]
Thank you very much, another question if possible?
I saw under build you have ninja subfolder with python scripts, is there any guide on how to use them? I would like to use your system for building on android and other targets.

Thanks again

**Comment by MJansson** [comment]
There is documentation available at https://rampantpixels.github.io/foundation_lib/doc/build_page.html (it needs to be updated a bit regarding code signing for android once the next release is out since that also uses the separate json config now).

You can also ask me on Twitter if you have specific questions, I'm [@maniccoder](https://twitter.com/maniccoder)
